C++/0-1 Knapsack Problem.cpp
Added the solution for 0-1 knapsack problem
=> Create 0-1 Knapsack Problem.cpp

Java/file_copy_paste.java
Simple java program to copy and paste file using Java Character stream FileReader and FileWriter.
=> new java program to copy one file and paste it in another file

Java/Stack.java, Java/StackTest.java, Java/StackTest.txt
Implemented Menu Driven Program for Stack using Arrays in Java with Manual and Automated Testing using Junit:
- > Added Operations such as Push, Pop, Peek, Is Empty, Display and Exit.
- > Added Manual Test cases and Edge cases.
- > Added Automated Test cases and Edge cases using Junit framework.
=> Implemented Menu Driven Program for Stack using Arrays in Java with Manual and Automated Testing using Junit.

C++/binarySearchTree.cpp
This file includes basic operations performed in a binary search tree: insertion, searching and deletion.
=> Create Binary Search Tree file

C++/kadane.cpp
i have added a Kadane Algorithm,
Kadane's Algorithm is a famous algorithm used to find the maximum sum of a subarray within a given array of numbers. It efficiently handles both positive and negative values, making it a crucial tool for solving problems related to maximum subarray sum in computer science and data analysis. Kadane's Algorithm is widely used in various applications, including stock market analysis and image processing.
Algorithm are as follow
maxi=arr[0]
sum=0
1>sum=sum+arr[i]
2>maxi=maximum of sum and maxi
3>if sum<0 put sum=0
=> Add Kadane's Algorithm

C++/DFS ALGO.cpp
Added a C++ code for Depth First Search Algorithm!
=> DFS Algorithm

C++/Seive_of_Eratosthenes
Seive of Eratosthenes is a algorithm for efficiently calculating the prime numbers with less time complexity.
=> Seive_of_Eratosthenes

Javascript/arrayReduceTransformation.js, Javascript/filterElementsFromAnArray.js
Create Javascript/utility functions:
1. Array Reduce Transformation
2. Filter Elements From An Array
=> Create Javascript/utility functions

C++/To_find_keyword.c, C++/To_find_keyword.txt
Hey I want you to please add these two files in your repository as they contains the program to find the number of keywords in a given text file.
=> Program to find the number of keywords in a given text file !!!

C++/insertionSort.cpp
Insertion Sort Algorithm Added With Comments
=> Insertion Sort Algorithm

C++/kabaddi.c
check the game and accept my PULL REQUEST
=> added game of kabaddi in C

python/YouTube Video Downloader/Readme.md, python/YouTube Video Downloader/YTdownload.py
Contributing to hacktoberfest2023.
=> Code to download YouTube video.

C++/Longest Valid Parentheses
The Longest Valid Parentheses problem is a classic programming problem that asks for the length of the longest valid parentheses substring in a given string. A valid parentheses substring is one where every opening parenthesis has a matching closing parenthesis, and the parentheses are closed in the correct order.
For example, the string "(()" has a longest valid parentheses substring of length 2, which is "()". The string ")()())" has a longest valid parentheses substring of length 4, which is "()()".
The problem can be solved in linear time using a stack. The algorithm is as follows:
1. Initialize a stack and push a special element -1 to it. This element represents the index before the beginning of the string.
2. Iterate over the string, starting from the first character. * If the …
=> Create Longest Valid Parentheses

python/Tic_Tac_Toe.py
Followed all the rules and regulations, added a working file in python folder
=> added game in python

python/Insertion Sort/InsertionSort.py
I have created an insertion sort algorithm using python.
=> Insertion sort

gameViaJS/index.html, gameViaJS/script.js, gameViaJS/style.css
Check the game, it tests how fast you can react.
=> added a simple game using JS

C++/subArray.cpp
i added 3 subarray problems and there solutions in c++.. this is commonly asked in interviews for mnc.
=> kami-subArray-probs

C++/Stack.cpp
This C++ program implements a stack data structure using a dynamically allocated array. It defines functions to push and pop elements, check if the stack is empty or full, and display its contents. The program demonstrates the stack operations by pushing and popping elements and deallocates memory properly at the end.
=> Added Stack.cpp

Javascript/filterTruthyFromArray.js
This is a function which helps to filter truthy values from an array.
=> Added filterTruthy function for Javascript

C++/Bellman-Ford-Algo.cpp, package.json
Please consider my contribution. I have added Bellman-Ford Algorithm in the C++ folder.
=> Added Bellman-Ford Algorithm

python/luhns-algo-checker.py
Added a working file in python folder
=> Added a card checking program in python

python/Sudoku_Solver.py
Hi, This is a contribution for Hacktoberfest, where I added a sudoku solver as a python project
=> feat: Added a Sudoku Solver in python directory

C++/OOPS Concepts/advanced-OOPS/Inheritance/Hybrid_Inheritance.cpp, C++/OOPS Concepts/advanced-OOPS/Inheritance/Inheritance1.cpp, C++/OOPS Concepts/advanced-OOPS/Inheritance/Order_constructor_destructor.cpp, C++/OOPS Concepts/advanced-OOPS/Inheritance/inheritance_types.cpp
Concepts of Inheritance Added to the Repo .
=> Inheritance Files Added

Weather tool.python
To create a tool that generates weather reports, we'll need to utilize a weather API to fetch weather data and present it to the user. In this example, I'll use the OpenWeatherMap API to fetch weather data for a given location. You'll need to sign up for an API key from OpenWeatherMap (https://openweathermap.org/api) to use their service. #hacktoberfest2023 #hacktoberfest-accepted
=> Create Weather tool.python

Javascript/Accordion/app.js, Javascript/Accordion/index.html, Javascript/Accordion/styles.css
- When clicked, current target's body gets visible.
- If open, others get closed.
- If current target is already visible, it gets closed.
=> Vanilla javascript accordion

python/SegmentTree.py
Added a Segment Tree Data Structure
=> Added SegmentTree

Bash/calculate_storage.sh
=> bash calculate storage script

C++/permutation_sequence.cpp
I have added the code for finding the k-th permutation sequence in cpp along with the link to the question in leetcode
=> Added the code for permutation sequence

C++/EdmondKarp.cpp
Edmond Karp algorithm is an algorithm used to find the maximum flow through a directed or undirected graph. [Wikipedia ref](https://en.wikipedia.org/wiki/Edmonds%E2%80%93Karp_algorithm)
=> Added Edmond Karp Algorithm

python/findfactorial/find-factorial.py
Hi @Aditya-devp  have added find-factorial-numbers. I request you to pls review and merge my PR.
=> addded find-factorial

Guess Game.javascript
This code creates a simple "Guess the Number" game where the player has a limited number of attempts to guess a random number between 1 and 100. The player enters their guess, and the game provides feedback on whether the guess is too high or too low. The game ends when the player correctly guesses the number or uses all their attempts. #hacktoberfest2023 #hacktoberfest-accepted
=> Create Guess Game.javascript

C++/climbingStairs.cpp
->I have added solution to Climbing stairs problem.
->Refer the following leetcode link for reference : -  https://leetcode.com/problems/climbing-stairs/description/
=> Added solution for Climbing Stairs problem

python/rock_paper_scissors.py
- Added clear and well documented code for the game of Rock Paper Scissors.
- Simple CLI fun game with added functionalities of rounds and engaging emojis
=> Added code for Rock Paper Scissors game

python/Bubble sort/bubbleSort.py
new Bubble sort algorith created
=> bubble sort

C++/MaximumDepthOfBinaryTree.cpp, C++/NumberOfProvinces.cpp
->Added solution to Number of Provinces Leetcode problem
->Problem link:- https://leetcode.com/problems/number-of-provinces/
=> Added solution to Number of Provinces Leetcode problem

python/hungman.py
Created A game using Python "HungMan"
=> Added HungmanGame

C++/bubble_sort.cpp
=> Added bubble sort in c++

C++/selectionSort.cpp
Hey, this is a hacktoberfest contibution.
=> Added a selection sort program in cpp

Java/Queue_Algorithm.java
i have created queue using java programming language
=> Queue using java

Java/FascinatingNumber.java
=> Added FascinatingNumber java program

python/number_game.py
Add number_game.py to the python folder.
=> Add number_game.py

python/linear-array-finder/linear-array-finder.py
Hi @Aditya-devp i have added linear-array-finder. I request you to pls review and merge my PR.
=> addded file linear-array-finder using python programs

python/Weather_Forecast.py
- Added clear and beginner friendly code for a weather forecast application in python.
- Provides valuable parameters like Temperature, Pressure and Humidity.
- Includes a GUI interface for getting user input
=> Added python code for weather forecast application

Html/css/styles.css, Html/index.html, python/number_game.py
Add css for footer so it appears at the bottom of the page, as it was stuck in the centre of the page.
Formatted the HTML document to give it a cleaner look and feel.
=> Fix Footer and HTML format

Java/dp/Knapsack.java, Java/dp/LCS.java, Java/dp/Palindrome_Partitioning.java, Java/dp/Unbounded_Knapsack.java
Please merge my pr. I have added 4 questions on dp
- Knapsack 0/1
- Knapsack Unbounded
- LCS printing
- Palindrome Partitioning
=> Added 4 dp questions in java

python/quadratic_eqn.py, python/sha_256.py
Added a program that calculates the hash of strings using SHA256
=> New Program Added

DSA projects/Bellman_ford_algorithm.cpp
Added code for Bellman-ford-algorithm to find the shortest distance in a graph in C++
=> Added code for Bellman-ford algorithm

C++/Insertion_sort_using_doubly_linked_list.cpp
@Aditya-devp   Code for performing insertion sort of a list using doubly linked list.
=> Added code for Insertion sort using doubly linked list in cpp

Java/Java/Fibbonaci_Series.java, Java/Java/Fibonaci_Series.java
This code bas generates the Fibonacci Series for an given upper bound.
=> Sahil mandal15 fibonacci_series

lru_page replacement.c
=> Add implementation of LRU page replacement in C

python/quicxo.py
Added a game called quicxo implemented in Python
=> feat: Added Quicxo game in Python

Javascript/sudoku-game/index.html, Javascript/sudoku-game/index.js, Javascript/sudoku-game/style.css
Create a Simple Sudoku Game with HTML, CSS, and JavaScript
=> Basic Sudoku Game - HTML, CSS, JS

C++/Euler_Totient_Function.cpp, C++/Modular_multiplicative_inverse.cpp
Added Euler_Totient_Function.cpp and Modular_multiplicative_inverse.cpp  files in cpp. Do check out these methods have awesome  use in competitive coding.
=> 2 new algorithms added in cpp section .

Javascript/StepsBysufyanhabib/index.html, Javascript/StepsBysufyanhabib/script.js, Javascript/StepsBysufyanhabib/style.css
**Steps Project Description**
🙏Dear maintainer @Aditya-devp  Please accept my PR #213
I have made the following changes in this pull request:
- I added my project folder StepsBysufyanhabib in Javascript
- Combined HTML, CSS, and JavaScript to create a Steps project.
- Added a user interface for displaying and navigating through a series of steps.
- Included relevant information and user actions in each step.
I created this project to provide an interactive way to present a series of steps or information.
**Hacktoberfest Progress**
I am excited to share that I have successfully submitted 3 out of 4 Pull/Merge Requests for Hacktoberfest. I believe this project aligns with the Hacktoberfest spirit and hope that this Pull Request will be the final one for this exciting event.
I look forward …
=> I Create a Steps project

Java/BubbleSort.java
=> Added sort in java

python/savings_goal_calculator.py
Add a monthly savings goal calculator that allows a user to add they goal name, goal amount and their estiamted monthly savings.
It will then give a breakdown on how much is left and how long it will take.
=> Add savings_goal_calculator.py

Html/about-me.html, Html/index.html, Html/recent-posts.html
Add missing HTML tags from all html documents.
Format all HTML code for a cleaner look.
=> Add missing HTML tags.

Javascript/isStringPalindrome.js
Hi,
Can you please accept PR with hacktoberfest 2023 tags?
=> Added Palindrome program in javascript

DataStructuresInJs/Stack.js
Added folder for implementation of data structures in javascript
=> implement stack in js

DataStructuresInJs/Deque.js, DataStructuresInJs/Queue.js
implemented Queue data structure in js
=> implement queue in javascript

Java/BlackJack_Game.java
i have created black java game using java programming language .
=> Balck jack game created using java

python/knap_sack.py
- Knap Sack algorithm Added
- 
https://en.wikipedia.org/wiki/Knapsack_problem
=> Knap Sack algorithm Added

C++/T_Prime_algorithm.cpp
kindly add label of hacktober fest
=> added code of T-Prime algorithm

Java/dp/BestTeamWithNoConflicts.java, Java/dp/BestTimeToBuyAndSellStock.java, Java/dp/EditDistance.java
=> Create best team with no conflict

C++/Trapping_Rain_Water.cpp
Please Accept this for HacktoberFest 2023.
=> Added Trapping Rainwater.cpp

DataStructuresInJs/multiset.js, Javascript/NumberOfClosedIslands.js
created multiset in javascript
=> add multiset

Javascript/NestListIterator.js
=> add nestlistiterator

Java/dp/RegularExpressionMatching.java
created Regular Expression Matching
=> Regular Expression Matching

C++/graphs/Part-1 Introduction/L2 Graph Representation _ C++/Gfg.cpp, C++/graphs/Part-1 Introduction/L5 BFS Traversal in Graphs/BFS-of-graph.cpp, C++/graphs/Part-1 Introduction/L6 DFS Traversal in Graphs/DFS-of-Graph.cpp
Created a graphs foldere which contains most useful content for someone starting with graphs in cpp and dfoing in leetcode and gfg questions serialwise
=> Beggainer Friendly Graphs Series
